# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', 'custom_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingset',
            name='event',
        ),
        migrations.AddField(
            model_name='tevent',
            name='training_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TrainingSet'),
        ),
    ]
