# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0001_trainedmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='training_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TrainingSet'),
        ),
    ]
