# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0002_hyperregionrelation_hypertuberegionrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryregionresults',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='queryregionresults',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='queryregionresults',
            name='query',
        ),
        migrations.RemoveField(
            model_name='queryregionresults',
            name='query_region',
        ),
        migrations.RemoveField(
            model_name='queryregionresults',
            name='retrieval_event',
        ),
        migrations.RemoveField(
            model_name='queryregionresults',
            name='video',
        ),
        migrations.AddField(
            model_name='queryresults',
            name='query_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.QueryRegion'),
        ),
        migrations.DeleteModel(
            name='QueryRegionResults',
        ),
    ]
