# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-13 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_auto_20180612_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='subdir',
        ),
    ]
