# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_auto_20180120_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingset',
            name='built_ts',
        ),
    ]
