# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_remove_frame_subdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dvaapp.Frame'),
        ),
    ]
