# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0005_auto_20180617_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='materialized',
        ),
    ]
