# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_remove_region_materialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='end_frame',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='start_frame',
        ),
        migrations.RemoveField(
            model_name='tube',
            name='end_frame',
        ),
        migrations.RemoveField(
            model_name='tube',
            name='start_frame',
        ),
    ]
