# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0007_auto_20180621_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryresults',
            name='frame',
        ),
        migrations.AddField(
            model_name='queryresults',
            name='frame_index',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
