# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0008_auto_20180129_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='stream',
            field=models.BooleanField(default=False),
        ),
    ]
