# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0011_auto_20180309_0732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexentries',
            unique_together=set([]),
        ),
    ]
