# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 03:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0013_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstate',
            name='completed_processes',
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='pending_processes',
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='pending_tasks',
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='tasks',
        ),
        migrations.AddField(
            model_name='systemstate',
            name='process_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='redis_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
