# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0014_auto_20180507_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedvideo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
