# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-19 17:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0015_deletedvideo_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRestart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_event_pk', models.IntegerField()),
                ('launched_event_pk', models.IntegerField()),
                ('attempts', models.IntegerField(default=0)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('operation', models.CharField(default='', max_length=100)),
                ('queue', models.CharField(default='', max_length=100)),
                ('video_uuid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL')),
            ],
        ),
    ]
