# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-20 06:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0016_taskrestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstate',
            name='worker_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_ping',
            field=models.DateTimeField(null=True, verbose_name='date last ping'),
        ),
    ]
