# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 05:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0018_frameregionrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_frame_index', models.IntegerField()),
                ('target_frame_index', models.IntegerField()),
                ('source_segment_index', models.IntegerField(null=True)),
                ('target_segment_index', models.IntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Label')),
                ('source_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_region', to='dvaapp.Region')),
                ('target_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_region', to='dvaapp.Region')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='source_frame',
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='source_region',
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='target_frame',
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='target_region',
        ),
        migrations.RemoveField(
            model_name='frameregionrelation',
            name='video',
        ),
        migrations.DeleteModel(
            name='FrameRegionRelation',
        ),
    ]
