# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0019_auto_20180530_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionrelation',
            name='label',
        ),
        migrations.AddField(
            model_name='regionrelation',
            name='name',
            field=models.CharField(default='unnamed', max_length=400),
            preserve_default=False,
        ),
    ]
