# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0020_auto_20180530_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framelabel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='framelabel',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='framelabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='framelabel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='segmentlabel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='segmentlabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='segmentlabel',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='segmentlabel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videolabel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='videolabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='videolabel',
            name='video',
        ),
        migrations.AddField(
            model_name='tube',
            name='full_segment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tube',
            name='full_video',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FrameLabel',
        ),
        migrations.DeleteModel(
            name='SegmentLabel',
        ),
        migrations.DeleteModel(
            name='VideoLabel',
        ),
    ]
